dg = DG()
dg.build().addAbstract("A -> B  A -> C")
A = next(v for v in dg.vertices if v.graph.name == "A")
B = next(v for v in dg.vertices if v.graph.name == "B")
C = next(v for v in dg.vertices if v.graph.name == "C")
eB = dg.findEdge([A], [B])
assert eB
eC = dg.findEdge([A], [C])
assert eC
net = causality.Net(dg)
marking = causality.Marking(net)
marking.add(A, 6)
trace = causality.EventTrace(marking)
trace.add(1, causality.EdgeAction(eB))
trace.add(2, causality.EdgeAction(eC))
trace.add(3, causality.EdgeAction(eC))
trace.add(4, causality.EdgeAction(eC))
trace.add(5, causality.EdgeAction(eC))
trace.add(6, causality.EdgeAction(eC))
trace.add(7, causality.InputAction(B))
trace.add(7, causality.InputAction(B))
trace.add(7, causality.InputAction(B))
trace.add(7, causality.InputAction(B))
trace.print()
