from collections.abc import Callable
from typing import TypeAlias, overload

import mod

# EventTrace
#-----------------------------------------------------------------------------

class EdgeAction:
	edge: mod.DG.HyperEdge

	def applyTo(self, marking: Marking) -> None: ...

class InputAction:
	vertex: mod.DG.Vertex

	def applyTo(self, marking: Marking) -> None: ...

class OutputAction:
	vertex: mod.DG.Vertex

	def applyTo(self, marking: Marking) -> None: ...

Action: TypeAlias = EdgeAction | InputAction | OutputAction


class EventTrace:
	def __init__(self, initialState: Marking) -> None: ...
	def add(self, time: float, a: Action) -> None: ...
	def print(self, printer: None | EventTracePrinter) -> str: ...

	@staticmethod
	@overload
	def load(dg: mod.DG, f: str) -> EventTrace: ...
	@staticmethod
	@overload
	def load(net: Net, f: str) -> EventTrace: ...


# EventTracePrinter
# ----------------------------------------------------------------------------

class EventTracePrinter:
	maxPointsPerVertex: int
	logTime: bool
	logCount: bool

	def pushOptions(self, f: Callable[[mod.DG], str] | str) -> None: ...
	def pushVertexVisible(self, f: Callable[[mod.DG.Vertex], bool] | bool) -> None: ...
	def pushVertexOptions(self, f: Callable[[mod.DG.Vertex], str] | str) -> None: ...
	def setPreContent(self, f: Callable[[mod.DG], str] | str) -> None: ...
	def setPostContent(self, f: Callable[[mod.DG], str] | str) -> None: ...


# Petri
#-----------------------------------------------------------------------------

class Net:
	def __init__(self, dg: mod.DG) -> None: ...
	def syncSize(self) -> None: ...


class Marking:
	def __init__(self, net: Net) -> None: ...
	def syncSize(self) -> None: ...
	def add(self, v: mod.DG.Vertex | mod.Graph, c: int) -> int: ...
	def remove(self, v: mod.DG.Vertex | mod.Graph, c: int) -> int: ...
	def __getitem__(self, v: mod.DG.Vertex | mod.Graph) -> int: ...
	def getAllEnabled(self) -> list[mod.DG.HyperEdge]: ...
	def getNonZeroPlaces(self) -> list[mod.DG.Vertex]: ...
	def getEmptyPostPlaces(self, e: mod.DG.HyperEdge) -> list[mod.DG.Vertex]: ...
	def fire(self, e: mod.DG.HyperEdge) -> None: ...


class MarkingSet:
	def addIfNotSubset(self, m: Marking) -> bool: ...


# Stochsim
#-----------------------------------------------------------------------------

class Simulator:
	class DrawFunction:
		def syncSize(self) -> None: ...
		def draw(self) -> tuple[Action, float]: ...

	class DrawTimeExponential:
		def __call__(self, activitySum: float) -> float: ...

	class ExpandByStrategy:
		...

	class DrawMassAction:
		def __call__(self, state: Marking) -> Function: ...

		class Function(Simulator.DrawFunction):
			def __init__(self, dg: mod.DG,
				inputRate:    None | Callable[[mod.DG.Vertex],
					tuple[float, bool]] | tuple[float, bool],
				reactionRate: None | Callable[[mod.DG.HyperEdge],
					tuple[float, bool]] | tuple[float, bool],
				outputRate:   None | Callable[[mod.DG.Vertex],
					tuple[float, bool]] | tuple[float, bool]) -> None: ...


	@property
	def trace(self) -> EventTrace: ...
	def setOnIterationBegin(self, callback: None | Callable[[Simulator], None], interval: int = ...) -> None: ...
	def simulate(self, *,
		time: None | float = ...,
		advanceToEndTime: bool = ...,
		iterations: None | int = ...,
		keepNetworkOpen: bool = ...) -> EventTrace: ...
