import mod

from typing import Callable, List, Optional, overload, Tuple, Union

# EventTrace
#-----------------------------------------------------------------------------

class EdgeAction:
	edge: mod.DG.HyperEdge

	def applyTo(self, marking: Marking) -> None: ...

class InputAction:
	vertex: mod.DG.Vertex

	def applyTo(self, marking: Marking) -> None: ...

class OutputAction:
	vertex: mod.DG.Vertex

	def applyTo(self, marking: Marking) -> None: ...

Action = Union[EdgeAction, InputAction, OutputAction]


class EventTrace:
	def __init__(self, initialState: Marking) -> None: ...
	def add(self, time: float, a: Action) -> None: ...
	def print(self, printer: Optional[EventTracePrinter]) -> str: ...

	@staticmethod
	@overload
	def load(dg: mod.DG, f: str) -> EventTrace: ...
	@staticmethod
	@overload
	def load(net: Net, f: str) -> EventTrace: ...


# EventTracePrinter
# ----------------------------------------------------------------------------

class EventTracePrinter:
	maxPointsPerVertex: int
	logTime: bool
	logCount: bool

	def pushOptions(self, f: Union[Callable[[mod.DG], str], str]) -> None: ...
	def pushVertexVisible(self, f: Union[Callable[[mod.DG.Vertex], bool], bool]) -> None: ...
	def pushVertexOptions(self, f: Union[Callable[[mod.DG.Vertex], str], str]) -> None: ...
	def setPreContent(self, f: Union[Callable[[mod.DG], str], str]) -> None: ...
	def setPostContent(self, f: Union[Callable[[mod.DG], str], str]) -> None: ...


# Petri
#-----------------------------------------------------------------------------

class Net:
	def __init__(self, dg: mod.DG) -> None: ...
	def syncSize(self) -> None: ...


class Marking:
	def __init__(self, net: Net) -> None: ...
	def syncSize(self) -> None: ...
	def add(self, v: mod.DG.Vertex | mod.Graph, c: int) -> int: ...
	def remove(self, v: mod.DG.Vertex | mod.Graph, c: int) -> int: ...
	def __getitem__(self, v: mod.DG.Vertex | mod.Graph) -> int: ...
	def getAllEnabled(self) -> List[mod.DG.HyperEdge]: ...
	def getNonZeroPlaces(self) -> List[mod.DG.Vertex]: ...
	def getEmptyPostPlaces(self, e: mod.DG.HyperEdge) -> List[mod.DG.Vertex]: ...
	def fire(self, e: mod.DG.HyperEdge) -> None: ...


class MarkingSet:
	def addIfNotSubset(self, m: Marking) -> bool: ...


# Stochsim
#-----------------------------------------------------------------------------

class MassActionKinetics:
	def __init__(self, dg: mod.DG,
		inputRate: Union[Callable[[mod.DG.Vertex],
			Tuple[float, bool]], Tuple[float, bool]],
		reactionRate: Union[Callable[[mod.DG.HyperEdge],
			Tuple[float, bool]], Tuple[float, bool]],
		outputRate: Union[Callable[[mod.DG.Vertex],
			Tuple[float, bool]], Tuple[float, bool]]) -> None: ...
	def syncSize(self) -> None: ...
	def draw(self, m: Marking) -> Tuple[Action, float]: ...
