from collections.abc import Callable

import mod

class Model:
	def __init__(self, dg: mod.DG, ilpSolver: str=...) -> None: ...
	dg: mod.DG

	absGap: None | int

	def findSolutions(self, *, maxNumSolutions: int=..., verbosity: int=..., ilpVerbosity: int=...) -> SolutionRange: ...
	@staticmethod
	def load(dg: mod.DG, f: str, ilpSolver: str=..., verbosity: int=..., listModel: bool=...) -> Model: ...
	@staticmethod
	def loadString(dg: mod.DG, s: str, ilpSolver: str=..., verbosity: int=..., listModel: bool=...) -> Model: ...


class VarSumVertex: ...
class VarVertex: ...
class VarVertexGraph: ...
class VarSumEdge: ...
class VarEdge: ...
class VarSumCustom: ...
class VarCustom: ...
class Var: ...
class LinExp:
	def __init__(self, other: LinExp) -> None: ...
	def __add__(self, other: LinExp) -> LinExp: ...
	def __sub__(self, other: LinExp) -> LinExp: ...
	def __pos__(self) -> LinExp: ...
	def __neg__(self) -> LinExp: ...

class LinConstraint: ...


class Printer:
	def pushOutEdgeLabel(self, f: Callable[[mod.DG.Vertex], str] | str) -> None: ...
	def pushInEdgeLabel(self, f: Callable[[mod.DG.Vertex], str] | str) -> None: ...


class SolutionRange:
	model: Model

	def print(self, printer: Printer=..., data: mod.DGPrintData=...) -> None: ...


class Solution:
	model: Model

	def print(self, printer: Printer=..., data: mod.DGPrintData=...) -> tuple[str, str]: ...
