import enum
from collections.abc import Callable, Iterable
from typing import TypeVar, overload

import mod.protocols

from . import causality

_T = TypeVar("_T")


#-----------------------------------------------------------------------------
# Meta
#-----------------------------------------------------------------------------

# Collection
#-----------------------------------------------------------------------------

class Vec(list[_T]): ...

class _VecDGHyperEdge(Vec[DG.HyperEdge]): ...
class _VecDGVertex(Vec[DG.Vertex]): ...
class _VecDGStrat(Vec[DGStrat]): ...
class _VecGraph(Vec[Graph]): ...
class _VecPairGraphInt(Vec[tuple[Graph, int]]): ...
class _VecRCExpExp(Vec[RCExpExp]): ...
class _VecRule(Vec[Rule]): ...


# Function
#-----------------------------------------------------------------------------

class _Func_VecGraph:
	def __call__(self) -> Vec[Graph]: ...
class _Func_String:
	def __call__(self) -> str: ...

class _Func_BoolDerivation:
	def __call__(self, d: Derivation) -> bool: ...

class _Func_StringDG:
	def __call__(self, v: DG) -> str: ...
class _Func_CausalitySimulatorDrawFunctionCausalityMarking:
	def __call__(self, state: causality.Marking) -> causality.Simulator.DrawFunction: ...

class _Func_VoidDGVertex:
	def __call__(self, v: DG.Vertex) -> None: ...
class _Func_BoolDGVertex:
	def __call__(self, v: DG.Vertex) -> bool: ...
class _Func_StringDGVertex:
	def __call__(self, v: DG.Vertex) -> str: ...
class _Func_PairDoubleBoolDGVertex:
	def __call__(self, v: DG.Vertex) -> tuple[float, bool]: ...

class _Func_StringDGVertexInt:
	def __call__(self, v: DG.Vertex, dupNum: int) -> str: ...

class _Func_VoidDGHyperEdge:
	def __call__(self, e: DG.HyperEdge) -> None: ...
class _Func_BoolDGHyperEdge:
	def __call__(self, e: DG.HyperEdge) -> bool: ...
class _Func_StringDGHyperEdge:
	def __call__(self, e: DG.HyperEdge) -> str: ...
class _Func_PairDoubleBoolDGHyperEdge:
	def __call__(self, e: DG.HyperEdge) -> tuple[float, bool]: ...

class _Func_BoolGraph:
	def __call__(self, g: Graph) -> bool: ...
class _Func_IntGraph:
	def __call__(self, g: Graph) -> int: ...

class _Func_StringGraphDGBool:
	def __call__(self, g: Graph, dg: DG, first: bool) -> str: ...

class _Func_BoolGraphDGStratGraphStateBool:
	def __call__(self, g: Graph, gs: DGStrat.GraphState, first: bool) -> bool: ...

class _Func_VoidDGStratGraphState:
	def __call__(self, gs: DGStrat.GraphState) -> None: ...

class _Func_FloatFloat:
	def __call__(self, f: float) -> float: ...

class _Func_BoolCausalitySimulator:
	def __call__(self, sim: causality.Simulator) -> bool: ...
class _Func_VoidCausalitySimulator:
	def __call__(self, sim: causality.Simulator) -> None: ...

class _Func_BoolDGBuilderVecGraphVecGraph: ...


#-----------------------------------------------------------------------------
# Top-level non-meta
#-----------------------------------------------------------------------------

# Chem
#-----------------------------------------------------------------------------

class BondType(enum.Enum):
	Invalid = ...
	Single = ...
	Aromatic = ...
	Double = ...
	Triple = ...
def _bondTypeToString(self: BondType) -> str: ...


# Config
#-----------------------------------------------------------------------------

class LabelType(enum.Enum):
	String = ...
	Term = ...
def _LabelType__str__(self: LabelType) -> str: ...

class LabelRelation(enum.Enum):
	Isomorphism = ...
	Specialisation = ...
	Unification = ...
def _LabelRelation__str__(self: LabelRelation) -> str: ...

class LabelSettings:
	@overload
	def __init__(self, lt: LabelType, lr: LabelRelation) -> None: ...
	@overload
	def __init__(self, lt: LabelType, lr: LabelRelation, slr: LabelRelation) -> None: ...

class IsomorphismPolicy(enum.Enum):
	Check = ...
	TrustMe = ...
def _IsomorphismPolicy__str__(self: IsomorphismPolicy) -> str: ...

class SmilesClassPolicy(enum.Enum):
	NoneOnDuplicate = ...
	ThrowOnDuplicate = ...
	MapUnique = ...
def _SmilesClassPolicy__str__(self: SmilesClassPolicy) -> str: ...

class MDLOptions: ...

def _getAvailableILPSolvers() -> list[str]: ...


class Config:
	class Common:
		ignoreDeprecation: bool

		def __init__(self) -> None: ...

	class Stochsim:
		massActionImplementation: str

		def __init__(self) -> None: ...

	common: Common
	stochsim: Stochsim

	def __init__(self) -> None: ...

def getConfig() -> Config: ...


# Error
#-----------------------------------------------------------------------------

class LogicError(Exception): ...


# Derivation
#-----------------------------------------------------------------------------

class Derivation: ...
class Derivations: ...


# Misc
#-----------------------------------------------------------------------------

def rngUniformReal() -> float: ...


#-----------------------------------------------------------------------------
# dg
#-----------------------------------------------------------------------------

class DG:
	def __init__(self, *, labelSettings: LabelSettings=...,
		graphDatabase: Iterable[Graph]=...,
		graphPolicy: IsomorphismPolicy=...) -> None: ...
	def findVertex(self, g: Graph) -> DG.Vertex: ...
	@overload
	def findEdge(self, sources: list[DG.Vertex], targets: list[DG.Vertex]) -> DG.HyperEdge: ...
	@overload
	def findEdge(self, sourcesGraphs: list[Graph], targetGraphs: list[Graph]) -> DG.HyperEdge: ...
	def build(self,
		onNewVertex: None | Callable[[DG.Vertex], None] = None,
		onNewHyperEdge: None | Callable[[DG.HyperEdge], None] = None): ...
	def print(self, printer: DGPrinter=..., data: None | DGPrintData=...) -> tuple[str, str]: ...
	@staticmethod
	def load(graphDatabase: list[Graph], ruleDatabase: list[Rule], file: str, graphPolicy: IsomorphismPolicy=..., verbosity: int=...) -> DG: ...

	class Vertex:
		graph: Graph

	class HyperEdge:
		def print(self, printer: GraphPrinter=..., nomatchColour: str=..., matchColour: str=...) -> list[tuple[str, str]]: ...

	class Builder:
		@property
		def dg(self) -> DG: ...
		@property
		def isActive(self) -> bool: ...
		def addDerivation(self, d: Derivations, graphPolicy: IsomorphismPolicy=...) -> DG.HyperEdge: ...
		def addHyperEdge(self, e: DG.HyperEdge, graphPolicy: IsomorphismPolicy=...) -> DG.HyperEdge: ...
		def execute(self, strategy: DGStrat, *, verbosity: int=..., ignoreRuleLabelTypes: bool=...) -> ExecuteResult: ...
		def apply(self, graphs: Iterable[Graph], rule: Rule, onlyProper: bool=..., verbosity: int=..., graphPolicy: IsomorphismPolicy=...) -> list[DG.HyperEdge]: ...
		def addAbstract(self, description: str) -> AddAbstractResult: ...
		def load(self, ruleDatabase: Iterable[Rule], file: str, verbosity: int=...) -> None: ...

		class ExecuteResult:
			def list(self, *, withUniverse: bool=...) -> None: ...

		class AddAbstractResult:
			def getGraph(self, name: str) -> None | Graph: ...


class DGPrinter:
	def pushVertexVisible(self, f: Callable[[DG.Vertex], bool] | bool) -> None: ...
	def pushEdgeVisible(self, f: Callable[[DG.HyperEdge], bool] | bool) -> None: ...
	def pushVertexLabel(self, f: Callable[[DG.Vertex], str] | str) -> None: ...
	def pushEdgeLabel(self, f: Callable[[DG.HyperEdge], str] | str) -> None: ...
	def pushVertexColour(self, f: Callable[[DG.Vertex], str] | str, extendToEdges: bool=...) -> None: ...
	def pushEdgeColour(self, f: Callable[[DG.HyperEdge], str] | str) -> None: ...
	def setRotationOverwrite(self, f: Callable[[Graph], int] | int) -> None: ...
	def setMirrorOverwrite(self, f: Callable[[Graph], bool] | bool) -> None: ...
	def setImageOverwrite(self, f: Callable[[DG.Vertex, int], str] | str) -> None: ...


class DGPrintData:
	def __init__(self, dg: DG) -> None: ...


class DGStrat:
	class GraphState: ...

	def __rshift__(self, other: DGStrat) -> DGStrat: ...
	def __rrshift__(self, other: DGStrat) -> DGStrat: ...

	@staticmethod
	def makeAddStatic(onlyUniverse: bool, graphs: list[Graph], graphPolicy: IsomorphismPolicy) -> DGStrat: ...
	@staticmethod
	def makeAddDynamic(onlyUniverse: bool, graphsFunc: Callable[[], list[Graph]], graphPolicy: IsomorphismPolicy) -> DGStrat: ...
	@staticmethod
	def makeSequence(strats: list[DGStrat]) -> DGStrat: ...
	@staticmethod
	def makeParallel(strats: list[DGStrat]) -> DGStrat: ...
	@staticmethod
	def makeFilter(alsoUniverse: bool, p: Callable[[Graph, GraphState, bool], bool]) -> DGStrat: ...
	@staticmethod
	def makeExecute(func: Callable[[GraphState], None]) -> DGStrat: ...
	@staticmethod
	def makeRule(rule: Rule) -> DGStrat: ...
	@staticmethod
	def makeLeftPredicate(p: Callable[[Derivation], bool], strat: DGStrat) -> DGStrat: ...
	@staticmethod
	def makeRightPredicate(p: Callable[[Derivation], bool], strat: DGStrat) -> DGStrat: ...
	@staticmethod
	def makeRevive(strat: DGStrat) -> DGStrat: ...
	@staticmethod
	def makeRepeat(limit: int, strat: DGStrat) -> DGStrat: ...


#-----------------------------------------------------------------------------
# graph
#-----------------------------------------------------------------------------

class Graph(mod.protocols.LabelledGraph):
	name: str

	def aut(self, labelSettings: LabelSettings=...) -> GraphAutGroup: ...
	@overload
	def print(self) -> tuple[str, str]: ...
	@overload
	def print(self, first: GraphPrinter, second: None | GraphPrinter=...) -> tuple[str, str]: ...
	def getGMLString(self, withCoords: bool=...) -> str: ...
	def printGML(self, withCoords: bool=...) -> str: ...

	smilesWithIds: str

	def isomorphism(self, host: Graph, maxNumMatches: int=..., labelSettings: LabelSettings=...) -> int: ...
	def monomorphism(self, host: Graph, maxNumMatches: int=..., labelSettings: LabelSettings=...) -> int: ...

	def getVertexFromExternalId(self, id: int) -> Graph.Vertex: ...
	minExternalId: int
	maxExternalId: int

	@staticmethod
	def fromGMLString(     s: str, add: bool=..., printStereoWarnings: bool=...) -> Graph: ...
	@staticmethod
	def fromGMLFile(       f: str, add: bool=..., printStereoWarnings: bool=...) -> Graph: ...
	@staticmethod
	def fromGMLStringMulti(s: str, add: bool=..., printStereoWarnings: bool=...) -> list[Graph]: ...
	@staticmethod
	def fromGMLFileMulti(  f: str, add: bool=..., printStereoWarnings: bool=...) -> list[Graph]: ...

	@staticmethod
	def fromDFS(           s: str, add: bool=...) -> Graph: ...
	@staticmethod
	def fromDFSMulti(      s: str, add: bool=...) -> list[Graph]: ...

	@staticmethod
	def fromSMILES(        s: str, allowAbstract: bool=..., classPolicy: SmilesClassPolicy=..., add: bool=..., printStereoWarnings: bool=...) -> Graph: ...
	@staticmethod
	def fromSMILESMulti(   s: str, allowAbstract: bool=..., classPolicy: SmilesClassPolicy=..., add: bool=..., printStereoWarnings: bool=...) -> list[Graph]: ...

	@staticmethod
	def fromMOLString(     s: str, options: MDLOptions=..., add: bool=...) -> Graph: ...
	@staticmethod
	def fromMOLFile(       f: str, options: MDLOptions=..., add: bool=...) -> Graph: ...
	@staticmethod
	def fromMOLStringMulti(s: str, options: MDLOptions=..., add: bool=...) -> list[Graph]: ...
	@staticmethod
	def fromMOLFileMulti(  f: str, options: MDLOptions=..., add: bool=...) -> list[Graph]: ...
	@staticmethod
	def fromSDString(      s: str, options: MDLOptions=..., add: bool=...) -> list[Graph]: ...
	@staticmethod
	def fromSDFile(        f: str, options: MDLOptions=..., add: bool=...) -> list[Graph]: ...
	@staticmethod
	def fromSDStringMulti( s: str, options: MDLOptions=..., add: bool=...) -> list[list[Graph]]: ...
	@staticmethod
	def fromSDFileMulti(   f: str, options: MDLOptions=..., add: bool=...) -> list[list[Graph]]: ...

	@staticmethod
	def fromRXNString(     s: str, options: MDLOptions=..., add: bool=...): ...
	@staticmethod
	def fromRXNFile(       f: str, options: MDLOptions=..., add: bool=...): ...
	@staticmethod
	def fromRXNStringMulti(s: str, options: MDLOptions=..., add: bool=...): ...
	@staticmethod
	def fromRXNFileMulti(  f: str, options: MDLOptions=..., add: bool=...): ...


class GraphAutGroup: ...


class GraphPrinter: ...


def graphGMLString(s: str) -> Graph: ...
def graphGML(f: str) -> Graph: ...
def graphDFS(s: str) -> Graph: ...
def smiles(s: str, allowAbstract: bool, classPolicy: SmilesClassPolicy) -> Graph: ...
def mdlMOLString(s: str, addHydrogens: bool) -> Graph: ...
def mdlMOL(f: str, addHydrogens: bool) -> Graph: ...
def mdlSDString(s: str, addHydrogens: bool) -> list[Graph]: ...
def mdlSD(f: str, addHydrogens: bool) -> list[Graph]: ...


#-----------------------------------------------------------------------------
# rule
#-----------------------------------------------------------------------------

class RCEvaluator:
	def __init__(self, ruleDatabase: Iterable[Rule], labelSettings: LabelSettings=...) -> None: ...
	def eval(self, exp: RCExpExp, *, verbosity: int=...) -> list[Rule]: ...


class RCExpExp: ...

class RCExpUnion(RCExpExp):
	def __init__(self, es: Vec[RCExpExp]) -> None: ...
class RCExpId(RCExpExp):
	def __init__(self, g: Graph) -> None: ...
class RCExpBind(RCExpExp):
	def __init__(self, g: Graph) -> None: ...
class RCExpUnbind(RCExpExp):
	def __init__(self, g: Graph) -> None: ...

class RCExpComposeCommon(RCExpExp):
	def __init__(self, first: RCExpExp, second: RCExpExp, discardNonchemical: bool=..., maximum: bool=..., connected: bool=..., includeEmpty: bool=...) -> None: ...

class RCExpComposeParallel(RCExpExp):
	def __init__(self, first: RCExpExp, second: RCExpExp, discardNonchemical: bool=...) -> None: ...

class RCExpComposeSub(RCExpExp):
	def __init__(self, first: RCExpExp, second: RCExpExp, discardNonchemical: bool=..., allowPartial: bool=...) -> None: ...

class RCExpComposeSuper(RCExpExp):
	def __init__(self, first: RCExpExp, second: RCExpExp, discardNonchemical: bool=..., allowPartial: bool=..., enforceConstraints: bool=...) -> None: ...


class RCMatch:
	class Result: ...

	def compose(self, *, verbose: bool=...) -> Rule: ...
	def composeWithMaps(self, *, verbose: bool=...) -> RCMatch.Result: ...
	def composeAll(self, *, maximum: bool=..., verbose: bool=...) -> list[Rule]: ...
	def composeAllWithMaps(self, *, maximum: bool=..., verbose: bool=...) -> list[RCMatch.Result]: ...


class Rule(RCExpExp):
	name: str

	left: LeftGraph
	right: RightGraph

	@overload
	def print(self, printCombined: bool=...) -> tuple[str, str]: ...
	@overload
	def print(self, first: GraphPrinter, second: None | GraphPrinter=..., printCombined: bool=...) -> tuple[str, str]: ...
	def getGMLString(self, withCoords: bool=...) -> str: ...
	def printGML(self, withCoords: bool=...) -> str: ...
	def isomorphism(self, host: Rule, maxNumMatches: int=..., labelSettings: LabelSettings=...) -> int: ...
	def monomorphism(self, host: Rule, maxNumMatches: int=..., labelSettings: LabelSettings=...) -> int: ...


	def __rshift__(self, other: DGStrat) -> DGStrat: ...

	@staticmethod
	def fromGMLString(s: str, name: str=..., *, invert: bool=..., add: bool=..., printStereoWarnings: bool=...) -> Rule: ...
	@staticmethod
	def fromGMLFile(f: str, name: str=..., *, invert: bool=..., add: bool=..., printStereoWarnings: bool=...) -> Rule: ...
	@staticmethod
	def fromDFS(s: str, name: str=..., *, invert: bool=..., add: bool=...) -> Rule: ...

	class LeftGraph(mod.protocols.LabelledGraph):
		...
	class RightGraph(mod.protocols.LabelledGraph):
		...
