
def command(line: str) -> None: ...
def flushCommands() -> None: ...
def disableCommands() -> None: ...
def enableCommands() -> None: ...
def reopenCommandFile() -> None: ...

def summaryChapter(heading: str) -> None: ...
def summarySection(heading: str) -> None: ...
