#ifndef MOD_HYPERFLOW_MODELIMPLEMENTATIONVIEW_HPP
#define MOD_HYPERFLOW_MODELIMPLEMENTATIONVIEW_HPP

#include <mod/hyperflow/Model.hpp>

namespace mod::hyperflow {

// rst: .. class:: hyperflow::ModelImplementationView
// rst:
// rst:		This class serves as a view on a locked hyperflow model,
// rst:		to obtain visualisations and statistics from how the model is implemented internally.
// rst:
struct MOD_DECL ModelImplementationView {
	// rst:		.. function:: ModelImplementationView(std::shared_ptr<Model> model)
	// rst:
	// rst:			:throws: :class:`LogicError` if `!model`
	// rst:			:throws: :class:`LogicError` if `!model->isSpecificationLocked()`
	ModelImplementationView(std::shared_ptr<Model> model);
	// rst:		.. function:: std::string printExpandedVertex(dg::DG::Vertex v) const
	// rst:
	// rst:			Print the expanded flow network for the given vertex.
	// rst:
	// rst:			:returns: the name of the PDF-file which will be created in post-processing.
	// rst:			:throws: :class:`LogicError` if `!v`.
	// rst:			:throws: :class:`LogicError` if `v.getDG()` is not in the same as in the underlying model.
	std::string printExpandedVertex(dg::DG::Vertex v) const;
	// rst:		.. function:: std::string printExpandedVertex(std::shared_ptr<graph::Graph> g) const
	// rst:
	// rst:			Equivalent to using `dg::DG::findVertex` on the underlying derivation graph and calling the vertex version.
	std::string printExpandedVertex(std::shared_ptr<graph::Graph> g) const;
	// rst:		.. function:: std::string printExpanded() const
	// rst:
	// rst:			Print the complete expanded derivation graph.
	// rst:
	// rst:			:returns: the name of the PDF-file which will be created in post-processing.
	std::string printExpanded() const;
	// rst:		.. function:: std::string printEnumerationTree() const
	// rst:
	// rst:			Print the search tree generated by the solution enumeration.
	// rst:
	// rst:			:returns: the name of the generated file.
	std::string printEnumerationTree() const;
	// rst:		.. function:: std::string writeMILP() const
	// rst:		              std::string writeMILP(std::string filetype) const
	// rst:
	// rst:			Writes the internal (M)ILP implementation of the model to a file, in the given format.
	// rst:			The default format is ``lp``.
	// rst:
	// rst:			:returns: the name of the written file.
	// rst:			:throws: :class:`LogicError` if the solver does not support writing in the given format.
	std::string writeMILP() const;
	std::string writeMILP(std::string format) const;
	// rst:		.. function:: int getNumMILPVariables() const
	// rst:		              int getNumMILPConstraints() const
	// rst:
	// rst:			:returns: various statistics of the model implementation.
	int getNumMILPVariables() const;
	int getNumMILPConstraints() const;
private:
	std::shared_ptr<Model> model;
};

} // namespace mod::hyperflow

#endif // MOD_HYPERFLOW_MODELIMPLEMENTATIONVIEW_HPP