# Note: conda-forge has global pinning, e.g., of boost, so make sure we include
#       variations for those verions.
# https://github.com/conda-forge/conda-forge-pinning-feedstock/tree/main/recipe
python:
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - 3.12
boost:
  - 1.78.0  # currently globally pinned version in conda-forge
pin_run_as_build:
  python: x.x
  boost: x.x.x
