# Note: conda-forge has global pinning, e.g., of boost, so make sure we include
#       variations for those verions.
# https://github.com/conda-forge/conda-forge-pinning-feedstock/tree/main/recipe
python:
  - 3.11
  - 3.12
  - 3.13
  # can't add >= 3.14 before openbabel has build with it
  # see migration status: https://conda-forge.org/status/migration/?name=python314
  #- 3.14
libboost:
  - 1.88.0  # currently globally pinned version in conda-forge
pin_run_as_build:
  python: x.x
  libboost: x.x.x
