{% set version = environ.get('MOD_CONDA_BUILD_VERSION') %}

package:
  name: mod
  {% if version %}
  version: {{ version }}
  {% endif %}

source:
  {% if version %}
  path: {{ "../build/mod-" + version + ".tar.gz" }}
  {% endif %}

build:
  string: py{{ python | replace(".", "") }}_boost{{ boost | replace(".", "") }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - pkg-config
    - cmake
    # lib packages, needed here to make sure we get the exact same version
    #               as in the host environment
    - boost {{ boost }}
    - openbabel
    - python {{ python }}
    # Add both exe and py packages to the build environemnt
    # so configuration checks succeed and tests can be run.
    # exe packages
    - graphviz>=2.46.1  # to get the rsvg plugin
    - pdf2svg
    # - texlive-core
    # py packages
    - ipython
    - networkx
    - parse
    - typing_extensions
    # Add openbabel here to get pybel for test.
    - openbabel
  host:
    # lib packages
    - boost {{ boost }}
    - openbabel
    - python {{ python }}
  run:
    # lib packages
    - boost
    - openbabel
    - python {{ python }}
    # exe packages
    - graphviz>=2.46.1  # to get the rsvg plugin
    - pdf2svg
    # - texlive-core
    - make
    # py packages
    - ipython
    - networkx
    - parse
    - typing_extensions

test:
  commands:
    - mod -e "smiles('O').print()"
    - mod_post --install-format
    - mod -e "smiles('O').print()"
