formaldehyde = Graph.fromSMILES("C=O", "Formaldehyde")
glycolaldehyde = Graph.fromSMILES( "OCC=O", "Glycolaldehyde")
ketoEnol_F = Rule.fromGMLFile("keto_enol_forward.gml")
ketoEnol_B = Rule.fromGMLFile("keto_enol_backward.gml")
aldolAdd_F = Rule.fromGMLFile("aldol_addition_forward.gml")
aldolAdd_B = Rule.fromGMLFile("aldol_addition_backward.gml")
