#include <mod/py/Common.hpp>

#include <mod/dg/GraphInterface.hpp>
#include <mod/hyperflow/ModelImplementationView.hpp>

namespace mod::hyperflow::Py {

// rst: .. class:: hyperflow.ModelImplementationView
// rst:
// rst:		This class serves as a view on a locked hyperflow model,
// rst:		to obtain visualisations and statistics from how the model is implemented internally.
// rst:
void ModelImplementationView_doExport() {
	// rst:		.. method:: __init__(self, model)
	// rst:
	// rst:			:raises: :class:`LogicError` if ``model`` is ``None``.
	// rst:			:raises: :class:`LogicError` if ``not specificationLocked``
	py::class_<ModelImplementationView>("ModelImplementationView", py::no_init)
			.def(py::init<std::shared_ptr<Model>>())
			// rst:		.. method:: printExpandedVertex(v)
			// rst:		            printExpandedVertex(g)
			// rst:
			// rst:			Print the expanded flow network for an explicitly given vertex
			// rst:			or a vertex indicated by a given graph.
			// rst:			The graph version is equivalent to calling
			// rst:			``self.printExpandedVertex(dg.findVertex(g))``, where ``dg`` is the derivation graph
			// rst:			of the underlying model.
			// rst:
			// rst:			:returns: the name of the PDF-file which will be created in post-processing.
			// rst:			:raises: (the vertex version) :class:`LogicError` if ``not v``.
			// rst:			:raises: (the graph version) :class:`LogicError` if it is not represented in the underlying DG.
			.def("printExpandedVertex",
			     static_cast<std::string (ModelImplementationView::*)(dg::DG::Vertex) const>(&
				     ModelImplementationView::printExpandedVertex))
			.def("printExpandedVertex",
			     static_cast<std::string (ModelImplementationView::*)(std::shared_ptr<mod::graph::Graph>) const>(&
				     ModelImplementationView::printExpandedVertex))
			// rst:		.. method:: printExpanded()
			// rst:
			// rst:			Print the complete expanded derivation graph.
			// rst:
			// rst:			:returns: the name of the PDF-file which will be created in post-processing.
			.def("printExpanded", &ModelImplementationView::printExpanded)
			// rst:		.. method:: printEnumerationTree()
			// rst:
			// rst:			Print the search tree generated by the solution enumeration.
			// rst:
			// rst:			:returns: the name of the generated file.
			.def("printEnumerationTree", &ModelImplementationView::printEnumerationTree)
			// rst:		.. method:: writeMILP(self, format="lp")
			// rst:
			// rst:			Writes the internal (M)ILP implementation of the model to a file, in the given format.
			// rst:			Note that different ILP libraries can write different formats.
			// rst:
			// rst:			:param str format: the format to write the model in. Defaults to ``lp``.
			// rst:			:returns: the name of the written file.
			// rst:			:throws: :class:`LogicError` if the solver does not support writing in the given format.
			.def("writeMILP", static_cast<std::string(ModelImplementationView::*)(std::string) const>(
				     &ModelImplementationView::writeMILP),
			     py::args("format") = "lp")
			// rst:		.. attribute:: numMILPVariables
			// rst:		               numMILPConstraints
			// rst:
			// rst:			(Read-only) Various statistics of the model implementation.
			// rst:
			// rst:			:type: int
			.add_property("numMILPVariables", &ModelImplementationView::getNumMILPVariables)
			.add_property("numMILPConstraints", &ModelImplementationView::getNumMILPConstraints);
}

} // namespace mod::hyperflow::Py