name: Build Conda packages
on: push
jobs:
  Conda-Linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set PATH
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Update apt
      run: sudo apt update
    - name: Install pip dependencies
      run: |
        sudo apt install python3-pip
        pip3 install -r pyreqs/base.txt
    - name: Install apt dependencies
      run: sudo apt install -y $(bindep -b base | tr '\n' ' ')
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_MOD=no -DBUILD_POST_MOD=no
    - name: Make archive
      run: cd build && make dist
    - name: Build
      run: ./scripts/makeConda.sh
    - name: Archive result
      uses: actions/upload-artifact@v7
      with:
        name: conda-linux
        path: |
          conda/conda-bld
        retention-days: 7
