name: CI
on: [push, pull_request]
jobs:
  macOS:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Install Brew dependencies
      run: |
        brew bundle
        /usr/libexec/path_helper | sed -e 's/^PATH="//' -e 's/"; export PATH;//' | tr ":" "\n"  | tail -r >> $GITHUB_PATH
    - name: Install pip dependencies
      run: pip3 install -r requirements.txt
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_TESTING=on
    - name: Build
      run: cd build && make -j 2
    - name: Install
      run: cd build && sudo make install
    - name: Build tests
      run: cd build && make tests -j 2
    - name: Run tests
      run: cd build && ctest --output-on-failure -j 2
    - name: Run simple test
      run: mod -e "smiles('O').print()"
