name: Main tests

env:
  graphvizVersion: 14.1.2

on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set PATH
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Update apt
      run: sudo apt update
    - name: Install pip dependencies
      run: |
        sudo apt install python3-pip
        pip3 install -r requirements.txt
    - name: Install apt dependencies
      run: sudo apt install -y $(bindep -b testing | tr '\n' ' ')
    - name: Install Boost
      run: |
        wget https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.gz
        tar -xf boost_1_83_0.tar.gz
        cd boost_1_83_0
        ./bootstrap.sh --with-python=python3 --prefix=/opt/boost
        ./b2 -j 4 --with-python --with-graph --with-iostreams --with-test install
    - name: Install Graphviz
      run: |
        sudo apt install librsvg2-dev libpango1.0-dev libperl-dev
        wget https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/$graphvizVersion/graphviz-$graphvizVersion.tar.gz
        wget http://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
        tar -xzf graphviz-$graphvizVersion.tar.gz
        cd graphviz-$graphvizVersion
        ./configure --disable-swig
        make -j 4
        sudo make install
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      env:
        CXXFLAGS: -Werror
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_DOC=yes -DBUILD_TESTING=yes -DCMAKE_PREFIX_PATH==/opt/boost -DWITH_GUROBI=no -DWITH_CPLEX=no
    - name: Build
      run: cd build && make -j 4
    - name: Install
      run: cd build && sudo make install
    - name: Build tests
      run: cd build && make tests -j 4
    - name: Run tests
      run: cd build && ctest --output-on-failure -j 4
    - name: Run simple test
      run: mod -e "Graph.fromSMILES('O').print()"
  macOS:
    strategy:
      matrix:
        version: [14, 15, 26]
      fail-fast: false
    runs-on: macos-${{ matrix.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Install Brew dependencies
      run: |
        brew update
        brew bundle
        /usr/libexec/path_helper | sed -e 's/^PATH="//' -e 's/"; export PATH;//' | tr ":" "\n"  | tail -r >> $GITHUB_PATH
    - name: Set up virtual environment
      run: |
        python3 -m venv --system-site-packages $GITHUB_WORKSPACE/myVenv
        echo "$GITHUB_WORKSPACE/myVenv/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/myVenv" >> $GITHUB_ENV
    - name: Install pip dependencies
      run: pip3 install -r requirements.txt
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_DOC=yes -DBUILD_TESTING=yes -DWITH_GUROBI=no -DWITH_CPLEX=no
    - name: Build
      run: cd build && make -j 4
    - name: Install
      run: cd build && sudo make install
    - name: Build tests
      run: cd build && make tests -j 4
    - name: Run tests
      run: cd build && ctest --output-on-failure -j 4
    - name: Run simple test
      run: mod -e "Graph.fromSMILES('O').print()"
