name: Build on other platforms

on:
  push:
  pull_request:
    paths:
    - "libs/**"
    - "test/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Docker:
    strategy:
      matrix:
        image: [Fedora, Arch, Conda]  # Ubuntu is handled in Main and in Docker
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: Set PATH
      run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
    - name: Update apt
      run: sudo apt update
    - name: Install pip dependencies
      run: |
        sudo apt install python3-pip
        pip3 install -r pyreqs/base.txt
    - name: Install apt dependencies
      run: sudo apt install -y $(bindep -b base | tr '\n' ' ')
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_MOD=no -DBUILD_POST_MOD=no
    - name: Make archive
      run: cd build && make dist
    - name: Build
      run: docker build -t jakobandersen/mod:${{ matrix.image }}-test -f docker/${{ matrix.image }}.Dockerfile --build-arg j=4 .
